version: '12.3'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: node_typescript
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
